name: Tag and push npm package

on:
  push:
    branches:
    - "master"
jobs:
  publish:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@helsingborg-stad'

    - name: Publish and tag
      run: |
        npm ci
        npm version
        npm publish