name: Tag and push npm package

on:
  push:
    branches:
    - "master"
jobs:
  publish:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Install
      run: npm ci
      env:
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Version
      run: npm version patch
      env:
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Version
      run: npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}